"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class Time_t(object):
    __slots__ = ["sec", "nsec"]

    __typenames__ = ["int32_t", "int32_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.sec = 0
        self.nsec = 0

    def encode(self):
        buf = BytesIO()
        buf.write(Time_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ii", self.sec, self.nsec))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Time_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Time_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = Time_t()
        self.sec, self.nsec = struct.unpack(">ii", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if Time_t in parents: return 0
        tmphash = (0xde1d24a3a8ecb648) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if Time_t._packed_fingerprint is None:
            Time_t._packed_fingerprint = struct.pack(">Q", Time_t._get_hash_recursive([]))
        return Time_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Time_t._get_packed_fingerprint())[0]

